### ISSUE TITLE
Daily Stand Up Log

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/nightingale#2]
In this issue, at the end of each working day, please add a comment answering the following questions:

### Am I facing any blockers?

**Comment by thejoefriel** [comment]
### Date:
Mon 21st Jan 2018

### What issue(s) did I work on today?
No issues. 
- Created the project overview deck
- Had the project start workshop with the product owner
- Set up the product owners on github
- Wrote a summary and [put here](https://github.com/techforbetter/nightingale/issues/5)
- Created a few issues for project set up

### What issue do I plan to work on tomorrow?
#5 - Agree scrope
#6 - Finalise all user journeys and stories

### Am I facing any blockers?
No

**Comment by dupreesi** [comment]
### Date 
Mon 21st Jan 18
### What issue(s) did I work on today?
#3 - #7
I worked with @thejoefriel and @RamyAlshurafa on the last client workshop to decide on the app's features and the work flow together with the POs.

### What issue do I plan to work on tomorrow?
#5 and #6

Am I facing any blockers?
no

**Comment by AsalaKM** [comment]
### Date 
Mon 22nd Jan 18
### What issue(s) did I work on today?
#6 - #8 
I worked with @RamyAlshurafa on writing all issues to achieve the features each sprint.
also, I created the project environment on fegma to start working on it.

### What issue do I plan to work on tomorrow?
#8 

Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
### Date:
Tuesday 22nd Jan 19
### What issue(s) did I work on today?
#6 & #8 
Worked with @AsalaKM on listing a general perception of user stories.
also, start work on Figma prototype.
### What issue do I plan to work on tomorrow?
#8 
### Am I facing any blockers?
No

**Comment by dupreesi** [comment]
Date:
Tuesday 22nd Jan 19

What issue(s) did I work on today?
#6 & #8 #9
Worked with Joe on User stories and got inspiration by other chatbot apps

What issue do I plan to work on tomorrow?
#8

Am I facing any blockers?
No

**Comment by thejoefriel** [comment]
Date:
Tuesday 22nd Jan 19

What issue(s) did I work on today?
#6 & #8 #9
Worked with Simon on User stories, reconfirmed the flow and got inspiration by other chatbot apps
With Simon raised issue #12 for the team to agree some final elements on user flow before design prototype
Also start adding the confirmed users into github

What issue do I plan to work on tomorrow?
#12, #6 and #8

Am I facing any blockers?
We need to agree the final elements raised in #12 so I can enter all the issues on github

**Comment by dupreesi** [comment]
Date:
Wednesday 23rd Jan 19

What issue(s) did I work on today?
#8
I was impressed by the work done by @RamyAlshurafa and @AsalaKM on Figma. All I did was to create an alternative user flow with a top navbar...

What issue do I plan to work on tomorrow?
#8 trying to embed the Product Owner's thoughts into Figma and
#11 hopefully starting to prototype in Invision and looking at tutorials online.

Am I facing any blockers?
No

**Comment by thejoefriel** [comment]
Date:
Wednesday 23rd Jan 

What issue(s) did I work on today?
#13 
Figma is looking great so I mainly worked on #13 and I also set up further issues to cover everything needed for project set up

What issue do I plan to work on tomorrow?
I'm chasing the client so we can do:
#8 trying to embed the Product Owner's thoughts into Figma and
#10 I think it's also important to finalise tech stack / file structure so we I can finish all the issues

Am I facing any blockers?
No

**Comment by AsalaKM** [comment]
### Date:
Wednesday 23rd Jan 

### What issue(s) did I work on today?
#8 

### What issue do I plan to work on tomorrow?
#10
 I think I should go to think about the file structure.
Also, I will work with @RamyAlshurafa on the database schema

### Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
### Date:
Thursday  24th Jan 2019
### What issue(s) did I work on today?
#43  build Figma prototype 
#44 analysis the database schema, also create a chart flow for the app(proposal).
### What issue do I plan to work on tomorrow?
On Sunday after the weekend, I will work on #43 
### Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
### Date:
Sunday 27th Jan 2019
### What issue(s) did I work on today?
#43 worked with @AsalaKM on Figma to make it ready for user testing tomorrow.
read and search about `Dialogflow` and how to connect it with the server and how to implement the fulfillments webhooks.
### What issue do I plan to work on tomorrow?
#38  Work with @AsalaKM on file structure and codebase
### Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
### Date:
Sunday 28th Jan 2019
### What issue(s) did I work on today?
Work on dialogflow and set up a meeting with @dupreesi to recap what we did with dialogflow API, and #49 create a rough document to visualize how the app will interact with dialogflow.
also, update the database schema suggestion #44 
### What issue do I plan to work on tomorrow?
maybe if we agreed on the DB schema I can start to build it and add fake data (need an issue)
### Am I facing any blockers?
No

**Comment by AsalaKM** [comment]
### Date:
 Monday 28th Jan 2019

### What issue(s) did I work on today?
#40  finished set up for client/react side and server/express side.
#38 finished  set up initial codebase, Install initial agreed packages.
#42 set up code coverage and linking our website with travis
### What issue do I plan to work on tomorrow?
I will work on the common react components  

### Am I facing any blockers?
No

**Comment by thejoefriel** [comment]
Date:
Monday 28th Jan 2019

What issue(s) did I work on today?
#48 wrote the scripts and carried out the user testing, then synthesized the results and shared on this issue
#43 did some final tweaks ahead of user testing

What issue do I plan to work on tomorrow?
Agree schema
Need to discuss on stand up 

Am I facing any blockers?
No

**Comment by dupreesi** [comment]
Date:
Tues 29th Jan 2019

What issue(s) did I work on today?
#2 - Set up heroku
#55 - Initial dialogflow set up

What issue do I plan to work on tomorrow?
Carry on working #55

Am I facing any blockers?
Need to leave in the afternoon

**Comment by RamyAlshurafa** [comment]
Date:
Tues 30th Jan 2019

What issue(s) did I work on today?
#54 Set up database and build dummy data and test them.
#17 start on `register` backend.

What issue do I plan to work on tomorrow?
continue on #17 
maybe start with #18 

Am I facing any blockers?
No

**Comment by thejoefriel** [comment]
Date:
Weds 30th Jan

What did I work on?
Nothing 😟 was at workshop all day

What am I working on next?
#55

Am I facing any blockers!
No

**Comment by RamyAlshurafa** [comment]
### Date:
 Monday 28th Jan 2019

### What issue(s) did I work on today?
#17 finished the signup (backend)
#20  start on the login (backend), --almost end--
### What issue do I plan to work on tomorrow?
complete #17 
and start on #19 
### Am I facing any blockers?
no

**Comment by RamyAlshurafa** [comment]
### Date 
Sunday 3rd Feb 19
### What issue(s) did I work on today?
#20 - done
#19 started with login front end issue.
### What issue do I plan to work on tomorrow?
#18 sign up - frontEnd

Am I facing any blockers?
no

**Comment by dupreesi** [comment]
Date
Sunday 4th Feb 19

What issue(s) did I work on today?
- reviewing and merging PRs 
- shared session with Joe #70 
- wrote test for #28 
- started #24 

What issue do I plan to work on tomorrow?
#24 

Am I facing any blockers?
I'm travelling to my parents tomorrow. I will be working on the train in the morning and in the afternoon at home.

**Comment by RamyAlshurafa** [comment]
### Date 
Monday 4rd Feb 19
### What issue(s) did I work on today?
#18 
### What issue do I plan to work on tomorrow?
#30 (I can start with this after the standup meeting that's ok with all) I have pastoral care sessions in the morning with FACG6 students
###Am I facing any blockers?
no

**Comment by thejoefriel** [comment]
Date
Monday 4th Feb 19

What issue(s) did I work on today?
#73
shared session with Joe #70

What issue do I plan to work on tomorrow?
#15
Going to review the issues and update the priorities again

Am I facing any blockers?
No

**Comment by dupreesi** [comment]
Date
Tuesday 5th Feb 19

What issue(s) did I work on today?
#24 

What issue do I plan to work on tomorrow?
#24 and then see

Am I facing any blockers?
No

**Comment by AsalaKM** [comment]
### Date
Tuesday 5th Feb 19

### What issue(s) did I work on today?
#23  and  #30 

### What issue do I plan to work on tomorrow?

Going to check priorities, linked pages and the basic menu in the site.
Work with @RamyAlshurafa  on dashboard issues & Bio page

### Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
Date
Tuesday 5th Feb 19

What issue(s) did I work on today?
#81 work on the dashboard (backend)
#83 fixed the authentication issue in passport.

What issue do I plan to work on tomorrow?
#81 finish the dashboard (backend)
#80 start working on the dashboard (front) 

Am I facing any blockers?
No

**Comment by thejoefriel** [comment]
### Date
Tuesday 5th Feb 19

### What issue(s) did I work on today?
#23 and #30

* Create and design the landing & home pages
* Create the messages page  to view  an individual conversation messages/details (back & front)

### What issue do I plan to work on tomorrow?
* Going to check priorities, linked pages and the basic menu in the site.
* Work with @RamyAlshurafa  on dashboard issues & Bio page

### Am I facing any blockers?
No

**Comment by dupreesi** [comment]
### Date
Wed 6th Feb 19

### What issue(s) did I work on today?
#24

### What issue do I plan to work on tomorrow?
Carry on with #24
Then see

### Am I facing any blockers?
No

**Comment by thejoefriel** [comment]
### Date
Wed 6th Feb 19

### What issue(s) did I work on today?
#85 

### What issue do I plan to work on tomorrow?
#27 if the conversation chat issue is completed
Otherwise #21 

### Am I facing any blockers?
No

**Comment by dupreesi** [comment]
### Date
Thurs 7th Feb 19

### What issue(s) did I work on today?
#92

### What issue do I plan to work on tomorrow?
create follow-up issues for chatbot
#24 
### Am I facing any blockers?
No

**Comment by thejoefriel** [comment]
### Date
Fri 8th Feb 19

### What issue(s) did I work on today?
* Further styling of chat window - #95
* Add card handling in chat - #101
* Fix fulfillment bug - #100
* All flows should now end with user able to add more thoughts or check out other areas of the platform - #27

### What issue do I plan to work on tomorrow?
will see

### Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
### Date
Sunday 10th Feb 19

### What issue(s) did I work on today?
#32 

### What issue do I plan to work on tomorrow?
#32 

### Am I facing any blockers?
No

**Comment by thejoefriel** [comment]
### Date
Monday 11th Feb 19

### What issue(s) did I work on today?
#103

### What issue do I plan to work on tomorrow?
#108

### Am I facing any blockers?
No

**Comment by thejoefriel** [comment]
### Date
Monday 11th Feb 19

### What issue(s) did I work on today?
#107 

### What issue do I plan to work on tomorrow?
#108

### Am I facing any blockers?
No

**Comment by dupreesi** [comment]
### Date
Tues 12th Feb 19

### What issue(s) did I work on today?
PR and #24 

### What issue do I plan to work on tomorrow?
#96 and #104 
### Am I facing any blockers?
No

**Comment by dupreesi** [comment]
### Date
Wed 13th Feb 19

### What issue(s) did I work on today?
#133 

### What issue do I plan to work on tomorrow?
#133 and #134

### Am I facing any blockers?
No
